# Generated by Django 2.0 on 2017-12-21 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fighter',
            fields=[
                ('alias', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('avatar', models.ImageField(upload_to='avatars')),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre')),
                ('start_date', models.DateTimeField(verbose_name='Hora de inicio')),
                ('finish_date', models.DateTimeField(verbose_name='Hora final')),
                ('fighter_count', models.IntegerField(verbose_name='Nº luchadores')),
                ('category', models.IntegerField(choices=[(0, 'Pluma'), (1, 'Medio'), (2, 'Pesado')], default=1, verbose_name='Categoría')),
                ('fighters', models.ManyToManyField(to='main.Fighter', verbose_name='Luchadores')),
            ],
        ),
    ]
